### ISSUE TITLE
Why is it called "name" instead of "url"?

### ISSUE THREAD

**Issue by domenic** [spanicker/longtasks#1]
It seems to always be a URL.

**Comment by igrigorik** [comment]
Name is the generic identifier on PerformanceEntry objects [1], and we already have ResourceTiming/NavigationTiming that use it to communicate the URL [2]. Admittedly not the greatest semantics, but it is an established and well-known pattern in the RUM space.. I'd prefer that we stick with consistent nomenclature.

[1] https://w3c.github.io/performance-timeline/#the-performanceentry-interface
[2] https://w3c.github.io/resource-timing/#performanceresourcetiming

**Comment by domenic** [comment]
Got it, thanks!
